### ISSUE TITLE
Blaster Secondary Plant error powers

### ISSUE THREAD

**Issue by zenblack** [Reborn-Team/Hero-Designer-DB#111]
The current version of Mids Reborn has an error on the Blaster Plant Manipulation secondary.

Skewer, Thorn Burst and Ripper can take Defense Debuff enhancements in game but not currently in Mids.

Good luck and keep on truck'n!

**Comment by FelesNoctis** [comment]
Already slotted for correction as part of the overhaul:
Issue https://github.com/Reborn-Team/Hero-Designer-DB/issues/24
