### ISSUE TITLE
[Page 6] (Pri) Scrapper - Energy Melee

### ISSUE THREAD

**Issue by zethriller** [Reborn-Team/Hero-Designer-DB#112]
Add Energy Melee for Scrappers as per potential content associated with HC page 6.

**Comment by zethriller** [comment]
Done:
- Powerset barebones
- Energy Focus inherent (display only)
- Enhancements and sets adjusted to proper values (numbers cloned from Brute version)

**Comment by Bopper-CoH** [comment]
Finished.
