### ISSUE TITLE
[CONTENT BUG] (Sec) Leadership/zc_Leadership - Victory Rush

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#113]
**Describe the bug**
**The duration of Victory Rush in MIDS is incorrect.  MIDS also doesn't show the values of each separate Victory Rush buff.(I don't know if that is even possible to code in honestly.)** 

**To Reproduce**
**Leadership**
**Victory Rush and look at the duration of the power.  MIDS is showing only 2 seconds which I imagine is the casting time for activating the pseudo pet that grants the buff**
**Click Effects in the Victory Rush Tab.  Notice how there are no of the values for the different buffs**

**Screenshots**

_**KEEP IN MIND THESE ARE DOMINATOR VALUES.  I'M SURE THE VALUES DIFFER ON OTHER ARCHETYPES LIKE TANKERS AND DEFENDERS**_

![VICTORYRUSHDOMINATOR](https://user-images.githubusercontent.com/45674165/94207386-813c0d00-fe95-11ea-9876-7f73935e5301.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
**Windows 10**
 - Database Version [e.g. 20.0515]
**20.0515**

**Comment by FelesNoctis** [comment]
zc_Leadership is going to be removed soon, as it represents the Page 5 beta state and may no longer be accurate.

The **duration** on Victory Rush we'll definitely need to correct. Displaying each value separately _may be possible_, but I can't make any guarantees. Odds are the way Mids calculates power effects it would simply add them all together, so we'd need to look into other ways of displaying them.

**Comment by Tatertoddipher** [comment]
I figured the zc_ part was going to be removed but I wanted to list it anyway just to be on the safe side.  It's understandable that you may not be able to list each value separately but I just wanted to post the correction here because I was going over my list of Mids errors that I always wanted to fix.  I appreciate the consideration and the comment no matter what the conclusion may be!

**Comment by Bopper-CoH** [comment]
This is a very complicated power to deal with as it has conditionals that Mids currently can't handle. I can create the correct effects in terms of their numbers, but they won't show on your character (it would just be there when you look in the database for the details, most likely). I can force one of them to always happen, like...maybe a boss. But that's sort of fixing a clock by breaking it. It will be right twice a day, but...

**Comment by Bopper-CoH** [comment]
I thought about it a bit and there is one form of hackery I could do. I can add a slider that will represent either a Boss, Elite Boss, or AV. Since those are even spaced as +20% recovery and +10% endurance discount per rank jump, it would work. Sadly, there will be no way of representing the Base, Minion, and Lieutenent values. I'll push this out, as it is easy enough to revert if we want to do it differently.

**Comment by Bopper-CoH** [comment]
Closing this issue as I have added the above capabilities.
