### ISSUE TITLE
[CONTENT BUG](Sec) Dominator - Gravity Control: Singularity

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#114]
**Describe the bug**
**Mids Reborn is showing that _Dominator - Gravity Control: Singularity_ takes Archetype Sets, when in fact in game the power does not take Dominator Archetype Sets.**

**Screenshots**

![DOMINATORGRAVITYCONTROLSIGULARITY2](https://user-images.githubusercontent.com/45674165/94224689-1274a900-fec1-11ea-9425-02a9811be95f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
**Windows 10**
 - Database Version [e.g. 20.0515]
**20.0515**

**Comment by Bopper-CoH** [comment]
Fixed internally.
