### ISSUE TITLE
[CONTENT BUG] (Sec) Scrapper - Ninjitsu - Shinobi-Iri

### ISSUE THREAD

**Issue by stonekarma** [Reborn-Team/Hero-Designer-DB#115]
**Describe the bug**
Scrapper Ninjitsu Secondary, Shinobi-Iri description says: "This power can't be used at the same time as other leaping powers like Combat Jump or running powers like Super Speed."
**To Reproduce**
Look at the description for Shinobi-Iri. 
**Expected behavior**
Shinobi-Iri works with Combat Jumping and Super Speed. I was not able to test it with Super Jump

**Screenshots**

**Desktop (please complete the following information):**
Homecoming servers

**Additional context**

**Comment by Bopper-CoH** [comment]
Fixed the description. Also noticed the enhancements allowed were incorrect, so I updated those too. I did not look at the effects however.
