### ISSUE TITLE
[CONTENT BUG] (Sec) Blaster - Darkness Manipulation - Touch of the Beyond

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#116]
**Describe the bug**
When added to build, power is always granting bonuses.

**To Reproduce**
1. Create new Blaster
2. Select Darkness Manipulation
3. Add Touch of the Beyond
4. Check stat totals for recovery and regeneration bonuses

**Expected behavior**
Users should be able to toggle buffs on and off

**Resolution**
Open power in DB editor, check special flag for **Power is a Click-Buff**

**Screenshots**
![Touch Power Fix](https://i.imgur.com/Vs8r9gz.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App: 2.7.2.10
 - Database Version: 20.0927_DEV

**Comment by Bopper-CoH** [comment]
Fixed
