### ISSUE TITLE
[CONTENT BUG] (Inc) Judgement - Vorpal Radial

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#117]
**Describe the bug**
When added to build, power is always granting bonuses.

**To Reproduce**
1. Create new character
2. Open Incarnate window
3. Add Vorpal Radial Final Judgement or Vorpal Total Radial Judgement
4. Check stat totals for defense bonus

**Expected behavior**
Users should be able to toggle buffs on and off

**Resolution**
Open power in DB editor, check special flag for **Power is a Click-Buff**

**Screenshots**
![Incarnate Power Fix](https://i.imgur.com/AHIShv3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App: 2.7.2.10
 - Database Version: 20.0927_DEV

**Comment by Bopper-CoH** [comment]
The two Vorpal powers that had defense buff effects, I granted the click buff. Fixed internally.
