### ISSUE TITLE
[CONTENT BUG] (SEC) Sentinel: Beam Rifle - Refractor Beam 

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#118]
**Describe the bug**
Refractor Beam in MIDS shows that you can slot knockback sets but that's not true.

**Screenshots**
![Refractor](https://user-images.githubusercontent.com/45674165/100709947-f7209100-337c-11eb-92b3-9c3379fb320f.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Database Version [e.g. 20.0515]

**Additional context**

**Comment by Bopper-CoH** [comment]
Fixed
