### ISSUE TITLE
[CONTENT BUG] (Sec) Controller/Dominator: Carrion Creepers

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#119]
**Describe the bug**
_A clear and concise description of what the bug is._
Carrion Creepers is showing the incorrect duration.  It's showing 15 seconds instead of 120 seconds.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Open Mids
2. Click on Controller or Dominator AT
3. Select Plant Control
4. Select Carrion Creepers

**Expected behavior**
_A clear and concise description of what you expected to happen._
It should show the duration of 120 seconds.  I assume the 15 secs duration is probably the duration of each summoned vine?

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![Carrioncreepers](https://user-images.githubusercontent.com/45674165/103470466-96e88a80-4d40-11eb-91f0-7d41c25d8e71.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10 Home-64bit(10.0, build 18363)**
 - Browser [e.g. chrome, safari] **Firefox v84.0.1**
 - Application Version [e.g. 2.7.1.25] **Mids' Reborn v3.0.1.9**
 - Database Version [e.g. 20.0426] **Database Issue 27, Version 20.1225**

**Additional context**
_Add any other context about the problem here._

**Comment by Bopper-CoH** [comment]
This is a known bug. The priority system on displaying Duration of effects is bork'd.

**Comment by Bopper-CoH** [comment]
Closing this because it is not a database bug. This bug should be posted in Mids-Reborn.
