### ISSUE TITLE
[CONTENT BUG] (Sec) Dominator: Energy Assault - Power Up

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#120]
**Describe the bug**
***Power Up* from Energy Assault will bug out or remove a few powers of said build. This keeps the user from uploading an /Energy Assault build.**

**To Reproduce**
**Load a previous /Energy Assault build**

**Expected behavior**
**It should show that Power Up is selected**

**Screenshots**

![Powerup](https://user-images.githubusercontent.com/45674165/103756767-d41d7880-4fdd-11eb-834b-f895eb304349.png)
![Powerup2](https://user-images.githubusercontent.com/45674165/103756801-dd0e4a00-4fdd-11eb-960f-68a7cb15dd1c.png)

**Desktop (please complete the following information):**

-     OS: [e.g. iOS] Windows 10 Home-64bit(10.0, build 18363)
-     Browser [e.g. chrome, safari] **Firefox v84.0.1
-     Application Version [e.g. 2.7.1.25] Mids' Reborn v3.0.1.9
-     Database Version [e.g. 20.0426] Database Issue 27, Version 20.1225

**Additional context**
_**I know this has already been reported and received on Discord but I wanted to report this bug just in case to be sure it's not overlooked.**_

**Comment by Bopper-CoH** [comment]
This was already fixed internally. https://github.com/Reborn-Team/MidsReborn/commit/758c1e1cf28617a026c848e229f1090db0766dde
