### ISSUE TITLE
[CONTENT BUG] Heal Enhancement Sets have wrong Absorb values

### ISSUE THREAD

**Issue by Karzach** [Reborn-Team/Hero-Designer-DB#122]
App Name: Mids Reborn
App Version: 3.0.2.18 (Database Issue: 27, Version: 21.0111)
Bug to Report:  All of the healing IO sets have their absorb values not scaled to multiple affects (IE Numina's Convalescence Heal/Endurance shows 26.5% for Heal and Endurance Reduction, but shows 42.4% for Absorb).

In addition, the Preventative Medicine set specifically, the Hit Point and Regeneration values in the database are also not scaled correctly, where applicable.

Github Issue #: None

**Comment by Bopper-CoH** [comment]
Thanks. Fixed.
