### ISSUE TITLE
[Overhaul] (Sec) Blaster - Tactical Arrow

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#25]
- [x] Electrified Net Arrow
- [x] Glue Arrow
- [x] Ice Arrow
- [x] Upshot
- [x] Flash Arrow
- [x] Eagle Eye
- [x] Agility
- [x] ESD Arrow
- [x] Gymnastics

**Comment by Bopper-CoH** [comment]
Updated with Issue 27.
