### ISSUE TITLE
[Overhaul] (Sec) Corruptor - Trick Arrow

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#55]
- [x] Entangling Arrow
- [x] Flash Arrow
- [x] Glue Arrow
- [x] Ice Arrow
- [x] Poison Gas Arrow
- [x] Acid Arrow
- [x] Disruption Arrow
- [x] Oil Slick Arrow
- [x] EMP Arrow

**Comment by Bopper-CoH** [comment]
Finished with the Issue 27 updates.
