### ISSUE TITLE
[Overhaul] (Sec) Tanker - Stone Melee

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#84]
- [x] Stone Fist
- [x] Stone Mallet
- [x] Heavy Mallet
- [x] Taunt
- [x] Build Up
- [x] Fault
- [x] Tremor
- [x] Hurl Boulder
- [x] Seismic Smash

**Comment by zethriller** [comment]
Corrected an effect for Tremor: Wrong value and not marked as PvE.
Max targets for AoE changed from 10 to 16.
