### ISSUE TITLE
[CONTENT BUG] (Sec) Sentinel - Energy Aura - Power Armor

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#94]
**Describe the bug**
Power Armor power allows slotting Heal/Absorb enhancements and sets in the game, but Mids does not. Furthermore, it is probably miscalculating the extra hit points provided by this power.

**To Reproduce**
1. Set archetype as Sentinel
2. Select Energy Aura secondary
3. Choose Power Armor power
4. Attempt to slot heal/absorb

**Expected behavior**
Heal/Absorb enhancements should be able to be slotted. Also, bonus hitpoints should match in-game values.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Database Version DEV-20.0805

**Additional context**
Reported on HC forums: https://forums.homecomingservers.com/topic/21327-bug-in-energy-aura-for-sentinels/

**Comment by Bopper-CoH** [comment]
Fixed Internally. It now takes Heal and Resistance IOs and Set IOs. The resistance values were corrected from 0.525 scale to 0.75 scale and the Max HP effects were corrected from 1.5 scale to 1.0 scale.
