### ISSUE TITLE
[CONTENT BUG] (Sec) Masterminds - Charge Mastery - EM Pulse

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#95]
**Describe the bug**
The Power...Masterminds - Charge Mastery - EM Pulse is currently labeled as Masterminds - Charge Mastery - ESD
*Stolen from a discussion from Bopper* - (ESD) (sic)so it's a PBAoE stun instead of a TAoE hold(/sic) 

**Screenshots**
![ESD](https://user-images.githubusercontent.com/45674165/90329772-78424c80-df75-11ea-9bf8-74c7772888f6.jpg)
![EMPESD](https://user-images.githubusercontent.com/45674165/90329776-7aa4a680-df75-11ea-9484-287f34750712.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Database Version 20.0515

**Additional context**

**Comment by Bopper-CoH** [comment]
fixed internally
