### ISSUE TITLE
[CONTENT BUG] (Pri) Controller - Mind Control

### ISSUE THREAD

**Issue by Tatertoddipher** [Reborn-Team/Hero-Designer-DB#96]
**Describe the bug**
In MIDS the power **Terrify** is saying that it takes Accurate To-Hit Debuff sets but that is not the case in game.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Bopper-CoH** [comment]
Fixed. The To-Hit Debuff and Accurate To-Hit Debuff has been removed.
