### ISSUE TITLE
[CONTENT BUG] (Enh) Brute - Unrelenting Fury + Superior

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#97]
**Describe the bug**
Unable to place Unrelenting Fury when matching Brute's Fury is also slotted. (A blocks A, etc)

**To Reproduce**
1. Start Brute build
2. Add two attacks
3. Slot any Brute's Fury enhancement in first attack (such as unique/F)
4. Attempt to slot matching Unrelenting Fury enhancement in second attack (as above, unique/F)

**Expected behavior**
One of each ATO set can be slotted together, they do not block each other. ATOs should only block themselves and/or the opposite-state normal/superior variant.

**Resolution**
Steps to fix:
1. Open Enhancement Editor
2. Open one of Unrelenting Fury or Superior variant
3. Change _MutEx_ to None
4. Repeat steps 2 and 3 for remaining affected enhancements

**Desktop (please complete the following information):**
 - App: 2.7.3.51_DEV
 - Database Version [e.g. 20.0525]

**Comment by Bopper-CoH** [comment]
Fixed internally in v3.0.2.18.
