### ISSUE TITLE
[CONTENT BUG] (Enh) Reactive Defenses: Scaling Resist

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#98]
**Describe the bug**
Unable to place Reactive Defenses: Scaling Resist when an ATO-E enhancement has been slotted.

**To Reproduce**
1. Start any AT build
2. Add offensive and defense-granting power
3. Slot any any ATO-E enhancement in first attack
4. Attempt to slot RD:SRD

**Expected behavior**
Reactive Defenses is not an ATO set, and should not have an exclusivity flag. RD:SRD is however a unique and should only be placed once.

**Resolution**
Steps to fix:
1. Open Enhancement Editor
2. Open Reactive Defenses: Scaling Resist Damage
3. Change _MutEx_ to None

**Desktop (please complete the following information):**
 - App: 2.7.3.51_DEV
 - Database Version [e.g. 20.0525]

**Comment by Bopper-CoH** [comment]
Fixed internally in v3.0.2.18.
