### ISSUE TITLE
[CONTENT BUG] (Sec) Widow - Fort/NW Teamwork - Mind Link

### ISSUE THREAD

**Issue by FelesNoctis** [Reborn-Team/Hero-Designer-DB#99]
**Describe the bug**
Defense scales are set to 1.428 (14.28%)
Resistance scale is set to 4.285 (42.85%)

**Expected behavior**
Defense scales should be 1.0 (10%)
Resistance scale should be 3.0 (30%)

**Comment by Bopper-CoH** [comment]
Fixed internally in v3.0.2.18.
